name: agrilink
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  get: ^4.6.6
  google_sign_in: ^7.1.0
  firebase_storage: ^12.4.5
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  riverpod_generator: ^2.6.5
  freezed: ^3.0.6
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/logo1.png
    - assets/images/app.png
    - assets/images/apple.png
    - assets/images/profile.png
