// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm3xQymg9_Yj2e3c8GrcJYkHrsi1C5bNQ',
    appId: '1:910137732574:android:b6c61bf6f0d71abe9e814f',
    messagingSenderId: '910137732574',
    projectId: 'agrilink-c63fc',
    storageBucket: 'agrilink-c63fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT60bnphnCd3X1l-w7pd41x2lQnbySZho',
    appId: '1:344907375780:ios:11c05263e3562e93ee7231',
    messagingSenderId: '344907375780',
    projectId: 'demoproject-fe097',
    storageBucket: 'demoproject-fe097.appspot.com',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAHLEpx3z02nLz8pvdvXkpRina15B329I',
    appId: '1:910137732574:web:39129dbb098b03089e814f',
    messagingSenderId: '910137732574',
    projectId: 'agrilink-c63fc',
    authDomain: 'agrilink-c63fc.firebaseapp.com',
    storageBucket: 'agrilink-c63fc.firebasestorage.app',
    measurementId: 'G-BHY8P40BY9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAHLEpx3z02nLz8pvdvXkpRina15B329I',
    appId: '1:910137732574:web:e48ed54a7b5a2a749e814f',
    messagingSenderId: '910137732574',
    projectId: 'agrilink-c63fc',
    authDomain: 'agrilink-c63fc.firebaseapp.com',
    storageBucket: 'agrilink-c63fc.firebasestorage.app',
    measurementId: 'G-948YVXCWS9',
  );
}
