// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfCz6xSuWzju3omXUPHYoBK-p04XCq8eA',
    appId: '1:737004274764:android:643145876d98571235a0e9',
    messagingSenderId: '737004274764',
    projectId: 'agrilink-470b6',
    storageBucket: 'agrilink-470b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4u_fF8HDSfUPLIYiLEOfm-EaTuIqLaKg',
    appId: '1:737004274764:ios:758d90e68ad330d235a0e9',
    messagingSenderId: '737004274764',
    projectId: 'agrilink-470b6',
    storageBucket: 'agrilink-470b6.firebasestorage.app',
    iosBundleId: 'com.agrilink.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVKnrlgTAJMCxiEFiiokwB52_SHycJAr0',
    appId: '1:737004274764:web:9c2ddcfe803fc96235a0e9',
    messagingSenderId: '737004274764',
    projectId: 'agrilink-470b6',
    authDomain: 'agrilink-470b6.firebaseapp.com',
    storageBucket: 'agrilink-470b6.firebasestorage.app',
    measurementId: 'G-RMQ46PNBPM',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAHLEpx3z02nLz8pvdvXkpRina15B329I',
    appId: '1:910137732574:web:e48ed54a7b5a2a749e814f',
    messagingSenderId: '910137732574',
    projectId: 'agrilink-c63fc',
    authDomain: 'agrilink-c63fc.firebaseapp.com',
    storageBucket: 'agrilink-c63fc.firebasestorage.app',
    measurementId: 'G-948YVXCWS9',
  );
}